-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 12:48:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NFC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NFC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NFC` DEFAULT CHARACTER SET utf8 ;
USE `NFC` ;

-- -----------------------------------------------------
-- Table `NFC`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NFC`.`user` ;

CREATE TABLE IF NOT EXISTS `NFC`.`user` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `pseudo` VARCHAR(256) NULL,
    `password` VARCHAR(256) NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFC`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NFC`.`car` ;

CREATE TABLE IF NOT EXISTS `NFC`.`car` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `model` VARCHAR(45) NULL,
    `places` VARCHAR(256) NULL,
    `consumption` VARCHAR(256) NULL,
    `comfort` VARCHAR(256) NULL,
    `view` VARCHAR(512) NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFC`.`park`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NFC`.`park` ;

CREATE TABLE IF NOT EXISTS `NFC`.`park` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(256) NULL,
    `location` VARCHAR(256) NULL,
    `car_id` INT NOT NULL,
    `name` VARCHAR(256) NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_park_car_idx` (`car_id` ASC) VISIBLE,
    CONSTRAINT `fk_park_car`
    FOREIGN KEY (`car_id`)
    REFERENCES `NFC`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
